paths:
  /api/v1/train:
    post:
      summary: Create a new train
      description: Membuat data kereta baru
      tags:
        - Train
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainInput'
      responses:
        '201':
          description: Train created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Train'
        '400':
          description: Bad request

    get:
      summary: Get all trains
      description: Melihat data kereta yang ada
      tags:
        - Train
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of trains
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Train'

  /api/v1/train/{id}:
    get:
      summary: Get train by ID
      description: Melihat detail kereta by ID
      tags:
        - Train
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Train found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Train'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a train
      description: Memperbarui data kereta by ID
      tags:
        - Train
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainInput'
      responses:
        '200':
          description: Train updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Train'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a train
      description: Menghapus data kereta by ID
      tags:
        - Train
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Train deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Train:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        code:
          type: string
        createdAt:
          type: string
          format: date-time
    TrainInput:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
        code:
          type: string
    ErrorMessage:
      type: object
      properties:
        message:
          type: string
  responses:
    NotFound:
      description: Data not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessage'
